void NewLine();
void EqualLine(bool , bool );
const char * EqualLineReturn();
//char * StringCombine(char* , char* );
void EqualLineText(char*);
int CreateMenu(char* , int , int , bool);
void clearscreen();
void MultiInputs(char*, char*, int, int , bool);
void CreateFile(char*,char*);
int FileExists(char*);